package expendiobebidas.vista;

import expendiobebidas.modelo.pojo.Promocion;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Nash
 */
public class Bebidas extends javax.swing.JPanel {

    /**
     * Creates new form Bebidas
     */
    public Bebidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogRegistrarBebida = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNombreBebida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spPrecioBebida = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        spStockMinimo = new javax.swing.JSpinner();
        lbStockActual = new javax.swing.JLabel();
        spStockActual = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        scrollDescripcionBebida = new javax.swing.JScrollPane();
        taDescripcionBebida = new javax.swing.JTextArea();
        btnGuardarRegistroBebida = new javax.swing.JButton();
        btnCancelarRegistroBebida = new javax.swing.JButton();
        cbPromocion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        scrollTblBebidas = new javax.swing.JScrollPane();
        tblBebidas = new javax.swing.JTable();
        btnAddBebida = new javax.swing.JButton();
        btnActualizarBebida = new javax.swing.JButton();
        btnEliminarBebida = new javax.swing.JButton();

        dialogRegistrarBebida.setTitle("Registrar Bebida");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese los datos de la bebida que guste registrar:");

        jLabel3.setText("Nombre de la bebida:");

        jLabel4.setText("Precio:");

        spPrecioBebida.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));

        jLabel5.setText("Stock Mínimo:");

        spStockMinimo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        lbStockActual.setText("Stock Actual:");

        spStockActual.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel6.setText("Descripción:");

        taDescripcionBebida.setColumns(20);
        taDescripcionBebida.setLineWrap(true);
        taDescripcionBebida.setRows(5);
        taDescripcionBebida.setWrapStyleWord(true);
        scrollDescripcionBebida.setViewportView(taDescripcionBebida);

        btnGuardarRegistroBebida.setText("Guardar");

        btnCancelarRegistroBebida.setText("Cancelar");

        jLabel7.setText("Promocion:");

        javax.swing.GroupLayout dialogRegistrarBebidaLayout = new javax.swing.GroupLayout(dialogRegistrarBebida.getContentPane());
        dialogRegistrarBebida.getContentPane().setLayout(dialogRegistrarBebidaLayout);
        dialogRegistrarBebidaLayout.setHorizontalGroup(
            dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRegistrarBebidaLayout.createSequentialGroup()
                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarRegistroBebida)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarRegistroBebida)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogRegistrarBebidaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addComponent(tfNombreBebida))
                            .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(spStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spPrecioBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbStockActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPromocion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spStockActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRegistrarBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollDescripcionBebida)
                .addContainerGap())
        );
        dialogRegistrarBebidaLayout.setVerticalGroup(
            dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegistrarBebidaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNombreBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spPrecioBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStockActual)
                    .addComponent(spStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDescripcionBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogRegistrarBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarRegistroBebida)
                    .addComponent(btnCancelarRegistroBebida)))
        );

        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("BEBIDAS");

        tblBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Stock Actual", "Descripción", "Promocion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTblBebidas.setViewportView(tblBebidas);

        btnAddBebida.setText("Añadir Bebida");

        btnActualizarBebida.setText("Actualizar Bebida");
        btnActualizarBebida.setEnabled(false);
        btnActualizarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBebidaActionPerformed(evt);
            }
        });

        btnEliminarBebida.setText("Eliminar Bebida");
        btnEliminarBebida.setEnabled(false);
        btnEliminarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollTblBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddBebida)
                                .addGap(122, 122, 122)
                                .addComponent(btnActualizarBebida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarBebida))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(scrollTblBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBebida)
                    .addComponent(btnActualizarBebida)
                    .addComponent(btnEliminarBebida))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBebidaActionPerformed
        // On BebidaController
    }//GEN-LAST:event_btnActualizarBebidaActionPerformed

    private void btnEliminarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBebidaActionPerformed
        // On BebidaController
    }//GEN-LAST:event_btnEliminarBebidaActionPerformed

    public JButton getBtnActualizarBebida() {
        return btnActualizarBebida;
    }

    public JButton getBtnAddBebida() {
        return btnAddBebida;
    }

    public JButton getBtnCancelarRegistroBebida() {
        return btnCancelarRegistroBebida;
    }

    public JButton getBtnEliminarBebida() {
        return btnEliminarBebida;
    }

    public JButton getBtnGuardarRegistroBebida() {
        return btnGuardarRegistroBebida;
    }

    public JSpinner getSpPrecioBebida() {
        return spPrecioBebida;
    }

    public JSpinner getSpStockActual() {
        return spStockActual;
    }

    public JSpinner getSpStockMinimo() {
        return spStockMinimo;
    }

    public JTextArea getTaDescripcionBebida() {
        return taDescripcionBebida;
    }

    public JTable getTblBebidas() {
        return tblBebidas;
    }

    public JTextField getTfNombreBebida() {
        return tfNombreBebida;
    }

    public JDialog getDialogRegistrarBebida() {
        return dialogRegistrarBebida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarBebida;
    private javax.swing.JButton btnAddBebida;
    private javax.swing.JButton btnCancelarRegistroBebida;
    private javax.swing.JButton btnEliminarBebida;
    private javax.swing.JButton btnGuardarRegistroBebida;
    private javax.swing.JComboBox<Promocion> cbPromocion;
    private javax.swing.JDialog dialogRegistrarBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbStockActual;
    private javax.swing.JScrollPane scrollDescripcionBebida;
    private javax.swing.JScrollPane scrollTblBebidas;
    private javax.swing.JSpinner spPrecioBebida;
    private javax.swing.JSpinner spStockActual;
    private javax.swing.JSpinner spStockMinimo;
    private javax.swing.JTextArea taDescripcionBebida;
    private javax.swing.JTable tblBebidas;
    private javax.swing.JTextField tfNombreBebida;
    // End of variables declaration//GEN-END:variables
}
