package expendiobebidas.vista;

import expendiobebidas.controlador.BebidaController;
import expendiobebidas.controlador.ClienteController;
import expendiobebidas.controlador.PromocionController;
import expendiobebidas.controlador.ProveedorController;
import expendiobebidas.controlador.ReportesController;
import java.awt.CardLayout;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author eugen
 */
public class Main extends javax.swing.JFrame {

    private expendiobebidas.vista.Bebidas panelBebidas;
    private expendiobebidas.vista.Clientes panelClientes;
    private expendiobebidas.vista.PedidoCliente panelPedidoClientes;
    private expendiobebidas.vista.PedidoProveedor panelPedidoProveedor;
    private expendiobebidas.vista.Promociones panelPromociones;
    private expendiobebidas.vista.Proveedores panelProveedores;
    private expendiobebidas.vista.Reportes panelReportes;
    private expendiobebidas.vista.Ventas panelVentas;
    private expendiobebidas.vista.Compra panelCompras;
    private JPanel panelPrincipal;
    private CardLayout cardLayout;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        panelPrincipal = new JPanel(cardLayout);
       
        
        panelBebidas = new Bebidas();
        new BebidaController(panelBebidas);
        panelClientes = new Clientes();
        new ClienteController(panelClientes);
        panelProveedores = new Proveedores();
        new ProveedorController(panelProveedores);
        panelPedidoClientes = new PedidoCliente();
        panelPedidoProveedor = new PedidoProveedor();
        panelPromociones = new Promociones();
        new PromocionController(panelPromociones);
        panelReportes = new Reportes();
        new ReportesController(panelReportes);
        panelVentas = new Ventas();
        panelCompras = new Compra();
        
        panelPrincipal.add(panelBebidas, "Registrar Bebidas");
        panelPrincipal.add(panelClientes, "Registrar Clientes");
        panelPrincipal.add(panelProveedores, "Registrar Proveedores");
        panelPrincipal.add(panelPedidoClientes, "Registrar Pedidos para Cliente");
        panelPrincipal.add(panelPedidoProveedor, "Registar Pedidos para Proveedor");
        panelPrincipal.add(panelPromociones, "Crear Promocion");
        panelPrincipal.add(panelReportes, "Consultar Reportes");
        panelPrincipal.add(panelVentas, "Registrar Venta");
        panelPrincipal.add(panelCompras, "Registrar Compra");
        
        panelPrincipal.setPreferredSize(panelVentas.getPreferredSize());
        setContentPane(panelPrincipal);
        cardLayout.show(panelPrincipal, "Registrar Venta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBebida = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuProveedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidoProveedor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuPedidoCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPuntoVenta = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuCompra = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuReporte = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuPromocion = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(600, 450));

        jMenu1.setText("Registros");

        menuBebida.setText("Bebida");
        jMenu1.add(menuBebida);
        jMenu1.add(jSeparator1);

        menuCliente.setText("Cliente");
        jMenu1.add(menuCliente);
        jMenu1.add(jSeparator2);

        menuProveedor.setText("Proveedor");
        jMenu1.add(menuProveedor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");

        menuPedidoProveedor.setText("Proveedor");
        jMenu2.add(menuPedidoProveedor);
        jMenu2.add(jSeparator3);

        menuPedidoCliente.setText("Cliente");
        jMenu2.add(menuPedidoCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transacciones");

        menuPuntoVenta.setText("Punto de venta");
        jMenu3.add(menuPuntoVenta);
        jMenu3.add(jSeparator4);

        menuCompra.setText("Compra");
        jMenu3.add(menuCompra);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        menuReporte.setText("Reporte por fecha");
        jMenu4.add(menuReporte);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Promociones");

        menuPromocion.setText("Nueva Promocion");
        jMenu5.add(menuPromocion);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Cerrar Sesion");

        menuCerrarSesion.setText("Cerrar Sesion");
        jMenu6.add(menuCerrarSesion);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }
    
    public JMenuItem getMenuBebida() {
        return menuBebida;
    }

    public JMenuItem getMenuCliente() {
        return menuCliente;
    }

    public JMenuItem getMenuPedidoCliente() {
        return menuPedidoCliente;
    }

    public JMenuItem getMenuPedidoProveedor() {
        return menuPedidoProveedor;
    }

    public JMenuItem getMenuPromocion() {
        return menuPromocion;
    }

    public JMenuItem getMenuProveedor() {
        return menuProveedor;
    }

    public JMenuItem getMenuPuntoVenta() {
        return menuPuntoVenta;
    }

    public JMenuItem getMenuReporte() {
        return menuReporte;
    }

    public JMenuItem getMenuCompra() {
        return menuCompra;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuItem menuBebida;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuPedidoCliente;
    private javax.swing.JMenuItem menuPedidoProveedor;
    private javax.swing.JMenuItem menuPromocion;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuPuntoVenta;
    private javax.swing.JMenuItem menuReporte;
    // End of variables declaration//GEN-END:variables
}
