package expendiobebidas.vista;

import expendiobebidas.controlador.BebidaController;
import expendiobebidas.controlador.ClienteController;
import expendiobebidas.controlador.CompraController;
import expendiobebidas.controlador.PedidoClienteController;
import expendiobebidas.controlador.PedidoProveedorController;
import expendiobebidas.controlador.PromocionController;
import expendiobebidas.controlador.ProveedorController;
import expendiobebidas.controlador.ReporteFechaController;
import expendiobebidas.controlador.VentasController;
import java.awt.CardLayout;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author eugen
 */
public class Main extends javax.swing.JFrame {

    private expendiobebidas.vista.Bebidas panelBebidas;
    private expendiobebidas.vista.Clientes panelClientes;
    private expendiobebidas.vista.PedidosClientes panelPedidoClientes;
    private expendiobebidas.vista.PedidoProveedor panelPedidoProveedor;
    private expendiobebidas.vista.Promociones panelPromociones;
    private expendiobebidas.vista.Proveedores panelProveedores;
    private expendiobebidas.vista.Ventas panelVentas;
    private expendiobebidas.vista.Compras panelCompras;
    private expendiobebidas.vista.ReporteFechas panelReporteFecha;
    private expendiobebidas.vista.ReporteVentaPorProducto panelReporteProducto;
    private expendiobebidas.vista.ReporteStockMinimo panelReporteStockMinimo;
    private expendiobebidas.vista.ReporteProductoMasVendido panelProductoMasVendido;
    private expendiobebidas.vista.ReporteProductoMenosVendido panelProductoMenosVendido;
    private expendiobebidas.vista.ReporteClienteNoVendido panelProductoNoVendidoCliente;
    private expendiobebidas.vista.ReporteClienteMasVendido panelProductoMasVendidoCliente;

    private JPanel panelPrincipal;
    private CardLayout cardLayout;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        panelPrincipal = new JPanel(cardLayout);
       
        
        panelBebidas = new Bebidas();
        new BebidaController(panelBebidas);
        panelClientes = new Clientes();
        new ClienteController(panelClientes);
        panelProveedores = new Proveedores();
        new ProveedorController(panelProveedores);
        panelPedidoClientes = new PedidosClientes();
        new PedidoClienteController(panelPedidoClientes);
        panelPedidoProveedor = new PedidoProveedor();
        new PedidoProveedorController(panelPedidoProveedor);
        panelPromociones = new Promociones();
        new PromocionController(panelPromociones);
        panelVentas = new Ventas();
        new VentasController(panelVentas);
        panelCompras = new Compras();
        new CompraController(panelCompras);
        panelReporteFecha = new ReporteFechas();
        new ReporteFechaController(panelReporteFecha);
        panelReporteProducto = new ReporteVentaPorProducto();
        panelReporteStockMinimo = new ReporteStockMinimo();
        panelProductoMasVendido = new ReporteProductoMasVendido();
        panelProductoMenosVendido = new ReporteProductoMenosVendido();
        panelProductoNoVendidoCliente = new ReporteClienteNoVendido();
        panelProductoMasVendidoCliente = new ReporteClienteMasVendido();

        
        panelPrincipal.add(panelBebidas, "Registrar Bebidas");
        panelPrincipal.add(panelClientes, "Registrar Clientes");
        panelPrincipal.add(panelProveedores, "Registrar Proveedores");
        panelPrincipal.add(panelPedidoClientes, "Registrar Pedidos para Cliente");
        panelPrincipal.add(panelPedidoProveedor, "Registar Pedidos para Proveedor");
        panelPrincipal.add(panelPromociones, "Crear Promocion");
        panelPrincipal.add(panelVentas, "Registrar Venta");
        panelPrincipal.add(panelCompras, "Registrar Compra");
        panelPrincipal.add(panelReporteFecha, "Ventas por fecha");
        panelPrincipal.add(panelReporteProducto, "Ventas Organizadas por Producto");
        panelPrincipal.add(panelReporteStockMinimo, "Productos con Stock Minimo");
        panelPrincipal.add(panelProductoMasVendido, "Reporte Producto Más Vendido");
        panelPrincipal.add(panelProductoMenosVendido, "Reporte Producto Menos Vendido");
        panelPrincipal.add(panelProductoNoVendidoCliente, "Reporte Producto No Vendido Por Cliente");
        panelPrincipal.add(panelProductoMasVendidoCliente, "Reporte Producto Más Vendido a un Cliente");

        
        panelPrincipal.setPreferredSize(panelVentas.getPreferredSize());
        setContentPane(panelPrincipal);
        cardLayout.show(panelPrincipal, "Registrar Venta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBebida = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuProveedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuPedidoProveedor = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuPedidoCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPuntoVenta = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuCompra = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuReporteFecha = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuVentaPorProducto = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuReporteStockMinimo = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        reporteProductoMasVendido = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuReporteMenosVendidos = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuReporteProductoNoVendidoCliente = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuReporteClienteMasVendido = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuPromocion = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(750, 600));
        setSize(new java.awt.Dimension(750, 600));

        jMenu1.setText("Registros");

        menuBebida.setText("Bebida");
        jMenu1.add(menuBebida);
        jMenu1.add(jSeparator1);

        menuCliente.setText("Cliente");
        jMenu1.add(menuCliente);
        jMenu1.add(jSeparator2);

        menuProveedor.setText("Proveedor");
        jMenu1.add(menuProveedor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");

        menuPedidoProveedor.setText("Proveedor");
        jMenu2.add(menuPedidoProveedor);
        jMenu2.add(jSeparator3);

        menuPedidoCliente.setText("Cliente");
        jMenu2.add(menuPedidoCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transacciones");

        menuPuntoVenta.setText("Punto de venta");
        jMenu3.add(menuPuntoVenta);
        jMenu3.add(jSeparator4);

        menuCompra.setText("Compra");
        jMenu3.add(menuCompra);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        menuReporteFecha.setText("Reporte por fecha");
        jMenu4.add(menuReporteFecha);
        jMenu4.add(jSeparator5);

        menuVentaPorProducto.setText("Reporte Ventas Organizadas por Producto");
        menuVentaPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentaPorProductoActionPerformed(evt);
            }
        });
        jMenu4.add(menuVentaPorProducto);
        jMenu4.add(jSeparator6);

        menuReporteStockMinimo.setText("Reporte Productos con Stock Mínimo");
        jMenu4.add(menuReporteStockMinimo);
        jMenu4.add(jSeparator7);

        reporteProductoMasVendido.setText("Reporte Producto Más Vendido");
        jMenu4.add(reporteProductoMasVendido);
        jMenu4.add(jSeparator8);

        menuReporteMenosVendidos.setText("Reporte Producto Menos Vendido");
        jMenu4.add(menuReporteMenosVendidos);
        jMenu4.add(jSeparator9);

        menuReporteProductoNoVendidoCliente.setText("Reporte Producto No Vendido por Cliente");
        jMenu4.add(menuReporteProductoNoVendidoCliente);
        jMenu4.add(jSeparator10);

        menuReporteClienteMasVendido.setText("Producto Más Vendido a Cliente");
        jMenu4.add(menuReporteClienteMasVendido);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Promociones");

        menuPromocion.setText("Nueva Promocion");
        jMenu5.add(menuPromocion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVentaPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentaPorProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVentaPorProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }
    
    public JMenuItem getMenuBebida() {
        return menuBebida;
    }

    public JMenuItem getMenuCliente() {
        return menuCliente;
    }

    public JMenuItem getMenuPedidoCliente() {
        return menuPedidoCliente;
    }

    public JMenuItem getMenuPedidoProveedor() {
        return menuPedidoProveedor;
    }

    public JMenuItem getMenuPromocion() {
        return menuPromocion;
    }

    public JMenuItem getMenuProveedor() {
        return menuProveedor;
    }

    public JMenuItem getMenuPuntoVenta() {
        return menuPuntoVenta;
    }

    public JMenuItem getMenuReporteFecha() {
        return menuReporteFecha;
    }

    public JMenuItem getMenuCompra() {
        return menuCompra;
    }

    public JMenuItem getMenuReporteCliente() {
        return menuReporteStockMinimo;
    }

    public JMenuItem getMenuReporteProducto() {
        return menuVentaPorProducto;
    }
    public JMenuItem getMenuReporteProductoMasVendido() {
    return reporteProductoMasVendido;
}

    public JMenuItem getMenuReporteProductoMenosVendido() {
        return menuReporteMenosVendidos;
    }

    public JMenuItem getMenuReporteProductoNoVendidoCliente() {
        return menuReporteProductoNoVendidoCliente;
    }

    public JMenuItem getMenuReporteProductoMasVendidoCliente() {
        return menuReporteClienteMasVendido;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem menuBebida;
    private javax.swing.JMenuItem menuCliente;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuPedidoCliente;
    private javax.swing.JMenuItem menuPedidoProveedor;
    private javax.swing.JMenuItem menuPromocion;
    private javax.swing.JMenuItem menuProveedor;
    private javax.swing.JMenuItem menuPuntoVenta;
    private javax.swing.JMenuItem menuReporteClienteMasVendido;
    private javax.swing.JMenuItem menuReporteFecha;
    private javax.swing.JMenuItem menuReporteMenosVendidos;
    private javax.swing.JMenuItem menuReporteProductoNoVendidoCliente;
    private javax.swing.JMenuItem menuReporteStockMinimo;
    private javax.swing.JMenuItem menuVentaPorProducto;
    private javax.swing.JMenuItem reporteProductoMasVendido;
    // End of variables declaration//GEN-END:variables
}
