/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package expendiobebidas.vista;

/**
 *
 * @author Nash
 */
public class Promociones extends javax.swing.JPanel {

    /**
     * Creates new form Promociones
     */
    public Promociones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogRegistrarPromociones = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollTaDescripcion = new javax.swing.JScrollPane();
        taDescripcionPromocion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spFechaInicioPromocion = new javax.swing.JSpinner();
        spFechaFinPromocion = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spDescuentoPromocion = new javax.swing.JSpinner();
        btnGuardarPromocion = new javax.swing.JButton();
        btnCancelarPromocion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spTblPromociones = new javax.swing.JScrollPane();
        tblPromociones = new javax.swing.JTable();
        btnRegistrarPromocion = new javax.swing.JButton();
        btnActualizarPromocion = new javax.swing.JButton();
        btnElimarPromoción = new javax.swing.JButton();

        dialogRegistrarPromociones.setTitle("Registrar Promoción");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Ingrese los datos de la promoción a registrar");

        jLabel3.setText("Descripción de la promoción:");

        taDescripcionPromocion.setColumns(20);
        taDescripcionPromocion.setLineWrap(true);
        taDescripcionPromocion.setRows(5);
        taDescripcionPromocion.setWrapStyleWord(true);
        scrollTaDescripcion.setViewportView(taDescripcionPromocion);

        jLabel4.setText("Fecha de Inicio (dd/MM/yyyy HH:mm):");

        jLabel5.setText("Fecha de Fin (dd/MM/yyyy HH:mm):");

        spFechaInicioPromocion.setModel(new javax.swing.SpinnerDateModel());
        spFechaInicioPromocion.setEditor(new javax.swing.JSpinner.DateEditor(spFechaInicioPromocion, "dd/MM/yyyy HH:mm"));

        spFechaFinPromocion.setModel(new javax.swing.SpinnerDateModel());
        spFechaFinPromocion.setEditor(new javax.swing.JSpinner.DateEditor(spFechaFinPromocion, "dd/MM/yyyy HH:mm"));

        jLabel6.setText("Descuento:");

        spDescuentoPromocion.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        btnGuardarPromocion.setText("Guardar");

        btnCancelarPromocion.setText("Cancelar");

        javax.swing.GroupLayout dialogRegistrarPromocionesLayout = new javax.swing.GroupLayout(dialogRegistrarPromociones.getContentPane());
        dialogRegistrarPromociones.getContentPane().setLayout(dialogRegistrarPromocionesLayout);
        dialogRegistrarPromocionesLayout.setHorizontalGroup(
            dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegistrarPromocionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(dialogRegistrarPromocionesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(dialogRegistrarPromocionesLayout.createSequentialGroup()
                                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spFechaInicioPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spFechaFinPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(spDescuentoPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(scrollTaDescripcion)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRegistrarPromocionesLayout.createSequentialGroup()
                                .addComponent(btnGuardarPromocion)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarPromocion)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        dialogRegistrarPromocionesLayout.setVerticalGroup(
            dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegistrarPromocionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spFechaInicioPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spFechaFinPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(spDescuentoPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(dialogRegistrarPromocionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPromocion)
                    .addComponent(btnCancelarPromocion))
                .addContainerGap())
        );

        setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PROMOCIONES");

        tblPromociones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripción", "Descuento", "Fecha de Inicio", "Fecha de Fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTblPromociones.setViewportView(tblPromociones);

        btnRegistrarPromocion.setText("Añadir Promoción");

        btnActualizarPromocion.setText("Actualizar Promoción");
        btnActualizarPromocion.setEnabled(false);

        btnElimarPromoción.setText("Eliminar Promoción");
        btnElimarPromoción.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spTblPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarPromocion)
                        .addGap(97, 97, 97)
                        .addComponent(btnActualizarPromocion)
                        .addGap(18, 18, 18)
                        .addComponent(btnElimarPromoción)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTblPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPromocion)
                    .addComponent(btnActualizarPromocion)
                    .addComponent(btnElimarPromoción))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPromocion;
    private javax.swing.JButton btnCancelarPromocion;
    private javax.swing.JButton btnElimarPromoción;
    private javax.swing.JButton btnGuardarPromocion;
    private javax.swing.JButton btnRegistrarPromocion;
    private javax.swing.JDialog dialogRegistrarPromociones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane scrollTaDescripcion;
    private javax.swing.JSpinner spDescuentoPromocion;
    private javax.swing.JSpinner spFechaFinPromocion;
    private javax.swing.JSpinner spFechaInicioPromocion;
    private javax.swing.JScrollPane spTblPromociones;
    private javax.swing.JTextArea taDescripcionPromocion;
    private javax.swing.JTable tblPromociones;
    // End of variables declaration//GEN-END:variables
}
